// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/services/account_deletion_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:horcrux/models/nostr_kinds.dart' as _i9;
import 'package:horcrux/models/relay_configuration.dart' as _i10;
import 'package:horcrux/models/share.dart' as _i8;
import 'package:horcrux/models/vault.dart' as _i13;
import 'package:horcrux/services/horcrux_notification_service.dart' as _i11;
import 'package:horcrux/services/logout_service.dart' as _i14;
import 'package:horcrux/services/ndk_service.dart' as _i4;
import 'package:horcrux/services/publish_service.dart' as _i2;
import 'package:horcrux/services/relay_scan_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:ndk/entities.dart' as _i7;
import 'package:ndk/ndk.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePublishBroadcastHandle_0 extends _i1.SmartFake implements _i2.PublishBroadcastHandle {
  _FakePublishBroadcastHandle_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdk_1 extends _i1.SmartFake implements _i3.Ndk {
  _FakeNdk_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdkService_2 extends _i1.SmartFake implements _i4.NdkService {
  _FakeNdkService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanningStatus_3 extends _i1.SmartFake implements _i5.ScanningStatus {
  _FakeScanningStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i4.NdkService {
  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setActiveRelays(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #setActiveRelays,
          [relayUrls],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> processGiftWrapFromForegroundPush(
    _i7.Nip01Event? event, {
    bool? allowLocalNotification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
          {#allowLocalNotification: allowLocalNotification},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i6.Future<_i7.Nip01Event?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.Nip01Event?>.value(),
      ) as _i6.Future<_i7.Nip01Event?>);

  @override
  _i6.Future<_i8.Share?> loadShareDataFromPublishedDistributionGiftWrap({
    required String? giftWrapEventId,
    required List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadShareDataFromPublishedDistributionGiftWrap,
          [],
          {
            #giftWrapEventId: giftWrapEventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i6.Future<_i8.Share?>.value(),
        returnValueForMissingStub: _i6.Future<_i8.Share?>.value(),
      ) as _i6.Future<_i8.Share?>);

  @override
  _i6.Future<String?> resolveVaultIdForGiftWrap(_i7.Nip01Event? giftWrap) => (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<({_i9.NostrKind kind, String recoveryRequestId})?> resolveRecoveryRequestIdForGiftWrap(
          _i7.Nip01Event? giftWrap) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveRecoveryRequestIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i6.Future<({_i9.NostrKind kind, String recoveryRequestId})?>.value(),
        returnValueForMissingStub:
            _i6.Future<({_i9.NostrKind kind, String recoveryRequestId})?>.value(),
      ) as _i6.Future<({_i9.NostrKind kind, String recoveryRequestId})?>);

  @override
  _i6.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i6.Future<void> queryHistoricalGiftWraps({required List<String>? relayUrls}) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryHistoricalGiftWraps,
          [],
          {#relayUrls: relayUrls},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i7.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i6.Future<_i7.Nip01Event?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.Nip01Event?>.value(),
      ) as _i6.Future<_i7.Nip01Event?>);

  @override
  _i6.Future<List<_i7.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i6.Future<List<_i7.Nip01Event?>>.value(<_i7.Nip01Event?>[]),
        returnValueForMissingStub: _i6.Future<List<_i7.Nip01Event?>>.value(<_i7.Nip01Event?>[]),
      ) as _i6.Future<List<_i7.Nip01Event?>>);

  @override
  _i6.Future<_i2.PublishBroadcastHandle> requestAccountVanish({
    required List<String>? relayUrls,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestAccountVanish,
          [],
          {
            #relayUrls: relayUrls,
            #reason: reason,
          },
        ),
        returnValue: _i6.Future<_i2.PublishBroadcastHandle>.value(_FakePublishBroadcastHandle_0(
          this,
          Invocation.method(
            #requestAccountVanish,
            [],
            {
              #relayUrls: relayUrls,
              #reason: reason,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.PublishBroadcastHandle>.value(_FakePublishBroadcastHandle_0(
          this,
          Invocation.method(
            #requestAccountVanish,
            [],
            {
              #relayUrls: relayUrls,
              #reason: reason,
            },
          ),
        )),
      ) as _i6.Future<_i2.PublishBroadcastHandle>);

  @override
  _i6.Future<_i3.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i6.Future<_i3.Ndk>.value(_FakeNdk_1(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Ndk>.value(_FakeNdk_1(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Ndk>);

  @override
  void setNdkForTesting(_i3.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disposePublishWorkerSync() => super.noSuchMethod(
        Invocation.method(
          #disposePublishWorkerSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [RelayScanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayScanService extends _i1.Mock implements _i5.RelayScanService {
  @override
  _i4.NdkService get ndkService => (super.noSuchMethod(
        Invocation.getter(#ndkService),
        returnValue: _FakeNdkService_2(
          this,
          Invocation.getter(#ndkService),
        ),
        returnValueForMissingStub: _FakeNdkService_2(
          this,
          Invocation.getter(#ndkService),
        ),
      ) as _i4.NdkService);

  @override
  void disposeSync() => super.noSuchMethod(
        Invocation.method(
          #disposeSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.RelayConfiguration>> getRelayConfigurations({bool? enabledOnly}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfigurations,
          [],
          {#enabledOnly: enabledOnly},
        ),
        returnValue: _i6.Future<List<_i10.RelayConfiguration>>.value(<_i10.RelayConfiguration>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i10.RelayConfiguration>>.value(<_i10.RelayConfiguration>[]),
      ) as _i6.Future<List<_i10.RelayConfiguration>>);

  @override
  _i6.Future<_i10.RelayConfiguration?> getRelayConfiguration(String? relayId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfiguration,
          [relayId],
        ),
        returnValue: _i6.Future<_i10.RelayConfiguration?>.value(),
        returnValueForMissingStub: _i6.Future<_i10.RelayConfiguration?>.value(),
      ) as _i6.Future<_i10.RelayConfiguration?>);

  @override
  _i6.Future<void> addRelayConfiguration(_i10.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #addRelayConfiguration,
          [relay],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateRelayConfiguration(_i10.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #updateRelayConfiguration,
          [relay],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeRelayConfiguration(String? relayId) => (super.noSuchMethod(
        Invocation.method(
          #removeRelayConfiguration,
          [relayId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> startRelayScanning({Duration? scanInterval}) => (super.noSuchMethod(
        Invocation.method(
          #startRelayScanning,
          [],
          {#scanInterval: scanInterval},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopRelayScanning() => (super.noSuchMethod(
        Invocation.method(
          #stopRelayScanning,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isScanningActive() => (super.noSuchMethod(
        Invocation.method(
          #isScanningActive,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i5.ScanningStatus> getScanningStatus() => (super.noSuchMethod(
        Invocation.method(
          #getScanningStatus,
          [],
        ),
        returnValue: _i6.Future<_i5.ScanningStatus>.value(_FakeScanningStatus_3(
          this,
          Invocation.method(
            #getScanningStatus,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i5.ScanningStatus>.value(_FakeScanningStatus_3(
          this,
          Invocation.method(
            #getScanningStatus,
            [],
          ),
        )),
      ) as _i6.Future<_i5.ScanningStatus>);

  @override
  _i6.Future<void> scanNow() => (super.noSuchMethod(
        Invocation.method(
          #scanNow,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncRelaysFromUrls(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #syncRelaysFromUrls,
          [relayUrls],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> ensureScanningStarted() => (super.noSuchMethod(
        Invocation.method(
          #ensureScanningStarted,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [HorcruxNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorcruxNotificationService extends _i1.Mock implements _i11.HorcruxNotificationService {
  @override
  _i6.Future<String> getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> setBaseUrl(String? override) => (super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [override],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> register({
    required String? fcmToken,
    required _i11.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fcmToken: fcmToken,
            #platform: platform,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deregister() => (super.noSuchMethod(
        Invocation.method(
          #deregister,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateToken({
    required String? newToken,
    required _i11.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [],
          {
            #newToken: newToken,
            #platform: platform,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> replaceConsents(List<String>? authorizedSenders) => (super.noSuchMethod(
        Invocation.method(
          #replaceConsents,
          [authorizedSenders],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<String> computeConsentList({
    required String? currentUserPubkey,
    required List<_i13.Vault>? vaults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeConsentList,
          [],
          {
            #currentUserPubkey: currentUserPubkey,
            #vaults: vaults,
          },
        ),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i6.Future<void> syncConsentList() => (super.noSuchMethod(
        Invocation.method(
          #syncConsentList,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConsent(String? senderPubkey) => (super.noSuchMethod(
        Invocation.method(
          #deleteConsent,
          [senderPubkey],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> tryPushForEvent({
    required _i7.Nip01Event? event,
    required _i9.NostrKind? kind,
    required _i13.Vault? vault,
    List<String>? relayHints,
    bool? recoveryApproved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryPushForEvent,
          [],
          {
            #event: event,
            #kind: kind,
            #vault: vault,
            #relayHints: relayHints,
            #recoveryApproved: recoveryApproved,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> push({
    required String? recipientPubkey,
    required String? title,
    required String? body,
    Map<String, dynamic>? eventJson,
    String? eventId,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [],
          {
            #recipientPubkey: recipientPubkey,
            #title: title,
            #body: body,
            #eventJson: eventJson,
            #eventId: eventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LogoutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutService extends _i1.Mock implements _i14.LogoutService {
  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetDatabase() => (super.noSuchMethod(
        Invocation.method(
          #resetDatabase,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
