// Mocks generated by Mockito 5.4.4 from annotations
// in horcrux/test/services/horcrux_notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:horcrux/models/backup_status.dart' as _i8;
import 'package:horcrux/models/recovery_request.dart' as _i12;
import 'package:horcrux/models/shard_data.dart' as _i11;
import 'package:horcrux/models/steward.dart' as _i9;
import 'package:horcrux/models/steward_status.dart' as _i10;
import 'package:horcrux/models/vault.dart' as _i7;
import 'package:horcrux/providers/vault_provider.dart' as _i6;
import 'package:horcrux/services/login_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyPair_0 extends _i1.SmartFake implements _i2.KeyPair {
  _FakeKeyPair_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i3.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.KeyPair> generateAndStoreNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #generateAndStoreNostrKey,
          [],
        ),
        returnValue: _i4.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #generateAndStoreNostrKey,
            [],
          ),
        )),
      ) as _i4.Future<_i2.KeyPair>);

  @override
  _i4.Future<_i2.KeyPair> importNsecKey(String? nsec) => (super.noSuchMethod(
        Invocation.method(
          #importNsecKey,
          [nsec],
        ),
        returnValue: _i4.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #importNsecKey,
            [nsec],
          ),
        )),
      ) as _i4.Future<_i2.KeyPair>);

  @override
  _i4.Future<_i2.KeyPair> importHexPrivateKey(String? hexPrivateKey) => (super.noSuchMethod(
        Invocation.method(
          #importHexPrivateKey,
          [hexPrivateKey],
        ),
        returnValue: _i4.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #importHexPrivateKey,
            [hexPrivateKey],
          ),
        )),
      ) as _i4.Future<_i2.KeyPair>);

  @override
  _i4.Future<_i2.KeyPair?> getStoredNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredNostrKey,
          [],
        ),
        returnValue: _i4.Future<_i2.KeyPair?>.value(),
      ) as _i4.Future<_i2.KeyPair?>);

  @override
  _i4.Future<_i2.KeyPair> initializeKey() => (super.noSuchMethod(
        Invocation.method(
          #initializeKey,
          [],
        ),
        returnValue: _i4.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #initializeKey,
            [],
          ),
        )),
      ) as _i4.Future<_i2.KeyPair>);

  @override
  _i4.Future<String?> getCurrentPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKey,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getCurrentPublicKeyBech32() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKeyBech32,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String> encryptText(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptText,
          [plaintext],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #encryptText,
            [plaintext],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> decryptText(String? encryptedText) => (super.noSuchMethod(
        Invocation.method(
          #decryptText,
          [encryptedText],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #decryptText,
            [encryptedText],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> clearStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearStoredKeys,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void resetCacheForTest() => super.noSuchMethod(
        Invocation.method(
          #resetCacheForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? npubToHex(String? npub) => (super.noSuchMethod(Invocation.method(
        #npubToHex,
        [npub],
      )) as String?);

  @override
  _i4.Future<String> encryptForRecipient({
    required String? plaintext,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptForRecipient,
          [],
          {
            #plaintext: plaintext,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #encryptForRecipient,
            [],
            {
              #plaintext: plaintext,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> decryptFromSender({
    required String? encryptedText,
    required String? senderPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFromSender,
          [],
          {
            #encryptedText: encryptedText,
            #senderPubkey: senderPubkey,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #decryptFromSender,
            [],
            {
              #encryptedText: encryptedText,
              #senderPubkey: senderPubkey,
            },
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [VaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultRepository extends _i1.Mock implements _i6.VaultRepository {
  MockVaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i7.Vault>> get vaultsStream => (super.noSuchMethod(
        Invocation.getter(#vaultsStream),
        returnValue: _i4.Stream<List<_i7.Vault>>.empty(),
      ) as _i4.Stream<List<_i7.Vault>>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Vault>> getAllVaults() => (super.noSuchMethod(
        Invocation.method(
          #getAllVaults,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Vault>>.value(<_i7.Vault>[]),
      ) as _i4.Future<List<_i7.Vault>>);

  @override
  _i4.Future<_i7.Vault?> getVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getVault,
          [id],
        ),
        returnValue: _i4.Future<_i7.Vault?>.value(),
      ) as _i4.Future<_i7.Vault?>);

  @override
  _i4.Future<void> saveVault(_i7.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #saveVault,
          [vault],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addVault(_i7.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #addVault,
          [vault],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVault(
    String? id,
    String? name,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVault,
          [
            id,
            name,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVault,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateBackupConfig(
    String? vaultId,
    ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      List<String> relays,
      String specVersion,
      _i8.BackupStatus status,
      List<_i9.Steward> stewards,
      int threshold,
      int totalKeys,
      String vaultId
    })? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [
            vaultId,
            config,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i8.BackupStatus status,
        List<_i9.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i4.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i8.BackupStatus status,
              List<_i9.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })?>.value(),
      ) as _i4.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i8.BackupStatus status,
            List<_i9.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })?>);

  @override
  _i4.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i10.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    int? acknowledgedDistributionVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
            #acknowledgedDistributionVersion: acknowledgedDistributionVersion,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addShardToVault(
    String? vaultId,
    _i11.ShardData? shard,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addShardToVault,
          [
            vaultId,
            shard,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.ShardData>> getShardsForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getShardsForVault,
          [vaultId],
        ),
        returnValue: _i4.Future<List<_i11.ShardData>>.value(<_i11.ShardData>[]),
      ) as _i4.Future<List<_i11.ShardData>>);

  @override
  _i4.Future<void> clearShardsForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #clearShardsForVault,
          [vaultId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteVaultContent(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVaultContent,
          [vaultId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isKeyHolderForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isKeyHolderForVault,
          [vaultId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> addRecoveryRequestToVault(
    String? vaultId,
    _i12.RecoveryRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecoveryRequestToVault,
          [
            vaultId,
            request,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRecoveryRequestInVault(
    String? vaultId,
    String? requestId,
    _i12.RecoveryRequest? updatedRequest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecoveryRequestInVault,
          [
            vaultId,
            requestId,
            updatedRequest,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.RecoveryRequest>> getRecoveryRequestsForVault(String? vaultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryRequestsForVault,
          [vaultId],
        ),
        returnValue: _i4.Future<List<_i12.RecoveryRequest>>.value(<_i12.RecoveryRequest>[]),
      ) as _i4.Future<List<_i12.RecoveryRequest>>);

  @override
  _i4.Future<_i12.RecoveryRequest?> getActiveRecoveryRequest(String? vaultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecoveryRequest,
          [vaultId],
        ),
        returnValue: _i4.Future<_i12.RecoveryRequest?>.value(),
      ) as _i4.Future<_i12.RecoveryRequest?>);

  @override
  _i4.Future<List<_i12.RecoveryRequest>> getAllRecoveryRequests() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecoveryRequests,
          [],
        ),
        returnValue: _i4.Future<List<_i12.RecoveryRequest>>.value(<_i12.RecoveryRequest>[]),
      ) as _i4.Future<List<_i12.RecoveryRequest>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
