// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/services/invitation_sending_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:horcrux/models/nostr_kinds.dart' as _i7;
import 'package:horcrux/models/share.dart' as _i6;
import 'package:horcrux/services/ndk_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ndk/entities.dart' as _i5;
import 'package:ndk/ndk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNdk_0 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i3.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setActiveRelays(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #setActiveRelays,
          [relayUrls],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> processGiftWrapFromForegroundPush(
    _i5.Nip01Event? event, {
    bool? allowLocalNotification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
          {#allowLocalNotification: allowLocalNotification},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i4.Future<_i5.Nip01Event?>.value(),
      ) as _i4.Future<_i5.Nip01Event?>);

  @override
  _i4.Future<_i6.Share?> loadShareDataFromPublishedDistributionGiftWrap({
    required String? giftWrapEventId,
    required List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadShareDataFromPublishedDistributionGiftWrap,
          [],
          {
            #giftWrapEventId: giftWrapEventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i4.Future<_i6.Share?>.value(),
      ) as _i4.Future<_i6.Share?>);

  @override
  _i4.Future<String?> resolveVaultIdForGiftWrap(_i5.Nip01Event? giftWrap) => (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<({_i7.NostrKind kind, String recoveryRequestId})?> resolveRecoveryRequestIdForGiftWrap(
          _i5.Nip01Event? giftWrap) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveRecoveryRequestIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i4.Future<({_i7.NostrKind kind, String recoveryRequestId})?>.value(),
      ) as _i4.Future<({_i7.NostrKind kind, String recoveryRequestId})?>);

  @override
  _i4.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i4.Future<void> queryHistoricalGiftWraps({required List<String>? relayUrls}) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryHistoricalGiftWraps,
          [],
          {#relayUrls: relayUrls},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i5.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i4.Future<_i5.Nip01Event?>.value(),
      ) as _i4.Future<_i5.Nip01Event?>);

  @override
  _i4.Future<List<_i5.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i4.Future<List<_i5.Nip01Event?>>.value(<_i5.Nip01Event?>[]),
      ) as _i4.Future<List<_i5.Nip01Event?>>);

  @override
  _i4.Future<_i2.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i4.Future<_i2.Ndk>.value(_FakeNdk_0(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Ndk>);

  @override
  void setNdkForTesting(_i2.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disposePublishWorkerSync() => super.noSuchMethod(
        Invocation.method(
          #disposePublishWorkerSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
