// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/services/invitation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:horcrux/models/backup_config.dart' as _i6;
import 'package:horcrux/models/backup_status.dart' as _i20;
import 'package:horcrux/models/nostr_kinds.dart' as _i9;
import 'package:horcrux/models/recovery_request.dart' as _i15;
import 'package:horcrux/models/relay_configuration.dart' as _i17;
import 'package:horcrux/models/share.dart' as _i8;
import 'package:horcrux/models/steward.dart' as _i19;
import 'package:horcrux/models/steward_status.dart' as _i14;
import 'package:horcrux/models/vault.dart' as _i13;
import 'package:horcrux/providers/vault_provider.dart' as _i12;
import 'package:horcrux/services/backup_service.dart' as _i18;
import 'package:horcrux/services/invitation_sending_service.dart' as _i16;
import 'package:horcrux/services/login_service.dart' as _i10;
import 'package:horcrux/services/ndk_service.dart' as _i4;
import 'package:horcrux/services/relay_scan_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:ndk/ndk.dart' as _i2;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNdk_0 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyPair_1 extends _i1.SmartFake implements _i3.KeyPair {
  _FakeKeyPair_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdkService_2 extends _i1.SmartFake implements _i4.NdkService {
  _FakeNdkService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanningStatus_3 extends _i1.SmartFake implements _i5.ScanningStatus {
  _FakeScanningStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupConfig_4 extends _i1.SmartFake implements _i6.BackupConfig {
  _FakeBackupConfig_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i4.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processGiftWrapFromForegroundPush(
    _i2.Nip01Event? event, {
    bool? allowLocalNotification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
          {#allowLocalNotification: allowLocalNotification},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i7.Future<_i2.Nip01Event?>.value(),
      ) as _i7.Future<_i2.Nip01Event?>);

  @override
  _i7.Future<_i8.Share?> loadShareDataFromPublishedDistributionGiftWrap({
    required String? giftWrapEventId,
    required List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadShareDataFromPublishedDistributionGiftWrap,
          [],
          {
            #giftWrapEventId: giftWrapEventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i7.Future<_i8.Share?>.value(),
      ) as _i7.Future<_i8.Share?>);

  @override
  _i7.Future<String?> resolveVaultIdForGiftWrap(_i2.Nip01Event? giftWrap) => (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<({_i9.NostrKind kind, String recoveryRequestId})?> resolveRecoveryRequestIdForGiftWrap(
          _i2.Nip01Event? giftWrap) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveRecoveryRequestIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i7.Future<({_i9.NostrKind kind, String recoveryRequestId})?>.value(),
      ) as _i7.Future<({_i9.NostrKind kind, String recoveryRequestId})?>);

  @override
  _i7.Future<String?> publishRecoveryRequest({
    required String? vaultId,
    required List<String>? stewardPubkeys,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishRecoveryRequest,
          [],
          {
            #vaultId: vaultId,
            #stewardPubkeys: stewardPubkeys,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i7.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<_i2.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
          },
        ),
        returnValue: _i7.Future<_i2.Nip01Event?>.value(),
      ) as _i7.Future<_i2.Nip01Event?>);

  @override
  _i7.Future<List<_i2.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
          },
        ),
        returnValue: _i7.Future<List<_i2.Nip01Event?>>.value(<_i2.Nip01Event?>[]),
      ) as _i7.Future<List<_i2.Nip01Event?>>);

  @override
  _i7.Future<_i2.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i7.Future<_i2.Ndk>.value(_FakeNdk_0(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Ndk>);

  @override
  void setNdkForTesting(_i2.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disposePublishWorkerSync() => super.noSuchMethod(
        Invocation.method(
          #disposePublishWorkerSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i10.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onSecureStorageReadFailure(_i7.Future<void> Function()? _onSecureStorageReadFailure) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSecureStorageReadFailure,
          _onSecureStorageReadFailure,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.KeyPair> generateAndStoreNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #generateAndStoreNostrKey,
          [],
        ),
        returnValue: _i7.Future<_i3.KeyPair>.value(_FakeKeyPair_1(
          this,
          Invocation.method(
            #generateAndStoreNostrKey,
            [],
          ),
        )),
      ) as _i7.Future<_i3.KeyPair>);

  @override
  _i7.Future<_i3.KeyPair> importNsecKey(String? nsec) => (super.noSuchMethod(
        Invocation.method(
          #importNsecKey,
          [nsec],
        ),
        returnValue: _i7.Future<_i3.KeyPair>.value(_FakeKeyPair_1(
          this,
          Invocation.method(
            #importNsecKey,
            [nsec],
          ),
        )),
      ) as _i7.Future<_i3.KeyPair>);

  @override
  _i7.Future<_i3.KeyPair> importHexPrivateKey(String? hexPrivateKey) => (super.noSuchMethod(
        Invocation.method(
          #importHexPrivateKey,
          [hexPrivateKey],
        ),
        returnValue: _i7.Future<_i3.KeyPair>.value(_FakeKeyPair_1(
          this,
          Invocation.method(
            #importHexPrivateKey,
            [hexPrivateKey],
          ),
        )),
      ) as _i7.Future<_i3.KeyPair>);

  @override
  _i7.Future<_i3.KeyPair?> getStoredNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredNostrKey,
          [],
        ),
        returnValue: _i7.Future<_i3.KeyPair?>.value(),
      ) as _i7.Future<_i3.KeyPair?>);

  @override
  _i7.Future<_i3.KeyPair> initializeKey() => (super.noSuchMethod(
        Invocation.method(
          #initializeKey,
          [],
        ),
        returnValue: _i7.Future<_i3.KeyPair>.value(_FakeKeyPair_1(
          this,
          Invocation.method(
            #initializeKey,
            [],
          ),
        )),
      ) as _i7.Future<_i3.KeyPair>);

  @override
  _i7.Future<String?> getCurrentPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKey,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getCurrentPublicKeyBech32() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKeyBech32,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String> encryptText(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptText,
          [plaintext],
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #encryptText,
            [plaintext],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> decryptText(String? encryptedText) => (super.noSuchMethod(
        Invocation.method(
          #decryptText,
          [encryptedText],
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #decryptText,
            [encryptedText],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> clearStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearStoredKeys,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void resetCacheForTest() => super.noSuchMethod(
        Invocation.method(
          #resetCacheForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? npubToHex(String? npub) => (super.noSuchMethod(Invocation.method(
        #npubToHex,
        [npub],
      )) as String?);

  @override
  _i7.Future<String> encryptForRecipient({
    required String? plaintext,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptForRecipient,
          [],
          {
            #plaintext: plaintext,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #encryptForRecipient,
            [],
            {
              #plaintext: plaintext,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> decryptFromSender({
    required String? encryptedText,
    required String? senderPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFromSender,
          [],
          {
            #encryptedText: encryptedText,
            #senderPubkey: senderPubkey,
          },
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #decryptFromSender,
            [],
            {
              #encryptedText: encryptedText,
              #senderPubkey: senderPubkey,
            },
          ),
        )),
      ) as _i7.Future<String>);
}

/// A class which mocks [VaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultRepository extends _i1.Mock implements _i12.VaultRepository {
  MockVaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i13.Vault>> get vaultsStream => (super.noSuchMethod(
        Invocation.getter(#vaultsStream),
        returnValue: _i7.Stream<List<_i13.Vault>>.empty(),
      ) as _i7.Stream<List<_i13.Vault>>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Stream<_i13.Vault?> watchVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #watchVault,
          [id],
        ),
        returnValue: _i7.Stream<_i13.Vault?>.empty(),
      ) as _i7.Stream<_i13.Vault?>);

  @override
  _i7.Future<List<_i13.Vault>> getAllVaults() => (super.noSuchMethod(
        Invocation.method(
          #getAllVaults,
          [],
        ),
        returnValue: _i7.Future<List<_i13.Vault>>.value(<_i13.Vault>[]),
      ) as _i7.Future<List<_i13.Vault>>);

  @override
  _i7.Future<_i13.Vault?> getVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getVault,
          [id],
        ),
        returnValue: _i7.Future<_i13.Vault?>.value(),
      ) as _i7.Future<_i13.Vault?>);

  @override
  _i7.Future<void> saveVault(_i13.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #saveVault,
          [vault],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addVault(_i13.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #addVault,
          [vault],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateVault(
    String? id,
    String? name,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVault,
          [
            id,
            name,
            content,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setPushEnabled(
    String? vaultId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPushEnabled,
          [
            vaultId,
            enabled,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVault,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateBackupConfig(
    String? vaultId,
    _i6.BackupConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [
            vaultId,
            config,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i6.BackupConfig?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i7.Future<_i6.BackupConfig?>.value(),
      ) as _i7.Future<_i6.BackupConfig?>);

  @override
  _i7.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i14.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    int? acknowledgedDistributionVersion,
    String? giftWrapEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
            #acknowledgedDistributionVersion: acknowledgedDistributionVersion,
            #giftWrapEventId: giftWrapEventId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isOwnedVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isOwnedVault,
          [vaultId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> addShareToVault(
    String? vaultId,
    _i8.Share? share, {
    bool? omitSharePayload = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addShareToVault,
          [
            vaultId,
            share,
          ],
          {#omitSharePayload: omitSharePayload},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.Share>> getSharesForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getSharesForVault,
          [vaultId],
        ),
        returnValue: _i7.Future<List<_i8.Share>>.value(<_i8.Share>[]),
      ) as _i7.Future<List<_i8.Share>>);

  @override
  _i7.Future<void> clearSharesForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #clearSharesForVault,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> upsertStewardRow({
    required String? id,
    required String? vaultId,
    required int? shareIndex,
    String? pubkey,
    String? name,
    bool? isOwner = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertStewardRow,
          [],
          {
            #id: id,
            #vaultId: vaultId,
            #shareIndex: shareIndex,
            #pubkey: pubkey,
            #name: name,
            #isOwner: isOwner,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> mergeVaultRowFromIncomingShare(
    String? vaultId,
    _i8.Share? share,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeVaultRowFromIncomingShare,
          [
            vaultId,
            share,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveOwnedVaultContent(
    String? vaultId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOwnedVaultContent,
          [
            vaultId,
            content,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVaultContent(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVaultContent,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isKeyHolderForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isKeyHolderForVault,
          [vaultId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> addRecoveryRequestToVault(
    String? vaultId,
    _i15.RecoveryRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecoveryRequestToVault,
          [
            vaultId,
            request,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateRecoveryRequestInVault(
    String? vaultId,
    String? requestId,
    _i15.RecoveryRequest? updatedRequest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecoveryRequestInVault,
          [
            vaultId,
            requestId,
            updatedRequest,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cleanupExpiredRecoverySessions() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredRecoverySessions,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.RecoveryRequest>> getRecoveryRequestsForVault(String? vaultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryRequestsForVault,
          [vaultId],
        ),
        returnValue: _i7.Future<List<_i15.RecoveryRequest>>.value(<_i15.RecoveryRequest>[]),
      ) as _i7.Future<List<_i15.RecoveryRequest>>);

  @override
  _i7.Future<_i15.RecoveryRequest?> getActiveRecoveryRequest(String? vaultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecoveryRequest,
          [vaultId],
        ),
        returnValue: _i7.Future<_i15.RecoveryRequest?>.value(),
      ) as _i7.Future<_i15.RecoveryRequest?>);

  @override
  _i7.Future<List<_i15.RecoveryRequest>> getAllRecoveryRequests() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecoveryRequests,
          [],
        ),
        returnValue: _i7.Future<List<_i15.RecoveryRequest>>.value(<_i15.RecoveryRequest>[]),
      ) as _i7.Future<List<_i15.RecoveryRequest>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [InvitationSendingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationSendingService extends _i1.Mock implements _i16.InvitationSendingService {
  MockInvitationSendingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NdkService get ndkService => (super.noSuchMethod(
        Invocation.getter(#ndkService),
        returnValue: _FakeNdkService_2(
          this,
          Invocation.getter(#ndkService),
        ),
      ) as _i4.NdkService);

  @override
  _i7.Future<String?> sendInvitationAcceptanceEvent({
    required String? inviteCode,
    required String? ownerPubkey,
    required List<String>? relayUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitationAcceptanceEvent,
          [],
          {
            #inviteCode: inviteCode,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> sendDenialEvent({
    required String? inviteCode,
    required String? ownerPubkey,
    required List<String>? relayUrls,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendDenialEvent,
          [],
          {
            #inviteCode: inviteCode,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
            #reason: reason,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> sendShareConfirmationEvent({
    required String? vaultId,
    required int? shareIndex,
    required String? ownerPubkey,
    required List<String>? relayUrls,
    int? distributionVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShareConfirmationEvent,
          [],
          {
            #vaultId: vaultId,
            #shareIndex: shareIndex,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
            #distributionVersion: distributionVersion,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> sendShareErrorEvent({
    required String? vaultId,
    required int? shareIndex,
    required String? ownerPubkey,
    required List<String>? relayUrls,
    required String? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShareErrorEvent,
          [],
          {
            #vaultId: vaultId,
            #shareIndex: shareIndex,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
            #error: error,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> sendInvitationInvalidEvent({
    required String? inviteCode,
    required String? inviteePubkey,
    required List<String>? relayUrls,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitationInvalidEvent,
          [],
          {
            #inviteCode: inviteCode,
            #inviteePubkey: inviteePubkey,
            #relayUrls: relayUrls,
            #reason: reason,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> sendKeyHolderRemovalEvent({
    required String? vaultId,
    required String? removedStewardPubkey,
    required List<String>? relayUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendKeyHolderRemovalEvent,
          [],
          {
            #vaultId: vaultId,
            #removedStewardPubkey: removedStewardPubkey,
            #relayUrls: relayUrls,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
}

/// A class which mocks [RelayScanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayScanService extends _i1.Mock implements _i5.RelayScanService {
  MockRelayScanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NdkService get ndkService => (super.noSuchMethod(
        Invocation.getter(#ndkService),
        returnValue: _FakeNdkService_2(
          this,
          Invocation.getter(#ndkService),
        ),
      ) as _i4.NdkService);

  @override
  void disposeSync() => super.noSuchMethod(
        Invocation.method(
          #disposeSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i17.RelayConfiguration>> getRelayConfigurations({bool? enabledOnly}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfigurations,
          [],
          {#enabledOnly: enabledOnly},
        ),
        returnValue: _i7.Future<List<_i17.RelayConfiguration>>.value(<_i17.RelayConfiguration>[]),
      ) as _i7.Future<List<_i17.RelayConfiguration>>);

  @override
  _i7.Future<_i17.RelayConfiguration?> getRelayConfiguration(String? relayId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfiguration,
          [relayId],
        ),
        returnValue: _i7.Future<_i17.RelayConfiguration?>.value(),
      ) as _i7.Future<_i17.RelayConfiguration?>);

  @override
  _i7.Future<void> addRelayConfiguration(_i17.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #addRelayConfiguration,
          [relay],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateRelayConfiguration(_i17.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #updateRelayConfiguration,
          [relay],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRelayConfiguration(String? relayId) => (super.noSuchMethod(
        Invocation.method(
          #removeRelayConfiguration,
          [relayId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> startRelayScanning({Duration? scanInterval}) => (super.noSuchMethod(
        Invocation.method(
          #startRelayScanning,
          [],
          {#scanInterval: scanInterval},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopRelayScanning() => (super.noSuchMethod(
        Invocation.method(
          #stopRelayScanning,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isScanningActive() => (super.noSuchMethod(
        Invocation.method(
          #isScanningActive,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i5.ScanningStatus> getScanningStatus() => (super.noSuchMethod(
        Invocation.method(
          #getScanningStatus,
          [],
        ),
        returnValue: _i7.Future<_i5.ScanningStatus>.value(_FakeScanningStatus_3(
          this,
          Invocation.method(
            #getScanningStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i5.ScanningStatus>);

  @override
  _i7.Future<void> scanNow() => (super.noSuchMethod(
        Invocation.method(
          #scanNow,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> syncRelaysFromUrls(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #syncRelaysFromUrls,
          [relayUrls],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> ensureScanningStarted() => (super.noSuchMethod(
        Invocation.method(
          #ensureScanningStarted,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i18.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i6.BackupConfig> createBackupConfiguration({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i19.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackupConfiguration,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i6.BackupConfig>.value(_FakeBackupConfig_4(
          this,
          Invocation.method(
            #createBackupConfiguration,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i6.BackupConfig>);

  @override
  _i7.Future<_i6.BackupConfig?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i7.Future<_i6.BackupConfig?>.value(),
      ) as _i7.Future<_i6.BackupConfig?>);

  @override
  _i7.Future<List<_i6.BackupConfig>> getAllBackupConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getAllBackupConfigs,
          [],
        ),
        returnValue: _i7.Future<List<_i6.BackupConfig>>.value(<_i6.BackupConfig>[]),
      ) as _i7.Future<List<_i6.BackupConfig>>);

  @override
  _i7.Future<void> updateBackupConfig(_i6.BackupConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [config],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBackupConfig,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.Share>> generateShamirShares({
    required String? content,
    required int? threshold,
    required int? totalShards,
    required String? creatorPubkey,
    required String? vaultId,
    required String? vaultName,
    required List<Map<String, String>>? stewards,
    String? ownerName,
    String? instructions,
    bool? pushEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateShamirShares,
          [],
          {
            #content: content,
            #threshold: threshold,
            #totalShards: totalShards,
            #creatorPubkey: creatorPubkey,
            #vaultId: vaultId,
            #vaultName: vaultName,
            #stewards: stewards,
            #ownerName: ownerName,
            #instructions: instructions,
            #pushEnabled: pushEnabled,
          },
        ),
        returnValue: _i7.Future<List<_i8.Share>>.value(<_i8.Share>[]),
      ) as _i7.Future<List<_i8.Share>>);

  @override
  _i7.Future<String> reconstructFromShares({required List<_i8.Share>? shares}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconstructFromShares,
          [],
          {#shares: shares},
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #reconstructFromShares,
            [],
            {#shares: shares},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateBackupStatus(
    String? vaultId,
    _i20.BackupStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupStatus,
          [
            vaultId,
            status,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i14.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    String? giftWrapEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
            #giftWrapEventId: giftWrapEventId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isBackupReady(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isBackupReady,
          [vaultId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i6.BackupConfig> mergeBackupConfig({
    required String? vaultId,
    int? threshold,
    List<_i19.Steward>? stewards,
    List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i6.BackupConfig>.value(_FakeBackupConfig_4(
          this,
          Invocation.method(
            #mergeBackupConfig,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i6.BackupConfig>);

  @override
  _i7.Future<void> handleContentChange(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #handleContentChange,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> redistributeForPushPreferenceChange({required String? vaultId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #redistributeForPushPreferenceChange,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> distributeKeysIfNecessary(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #distributeKeysIfNecessary,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i6.BackupConfig> saveBackupConfig({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i19.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i6.BackupConfig>.value(_FakeBackupConfig_4(
          this,
          Invocation.method(
            #saveBackupConfig,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i6.BackupConfig>);

  @override
  _i7.Future<_i6.BackupConfig> createAndDistributeBackup({required String? vaultId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAndDistributeBackup,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<_i6.BackupConfig>.value(_FakeBackupConfig_4(
          this,
          Invocation.method(
            #createAndDistributeBackup,
            [],
            {#vaultId: vaultId},
          ),
        )),
      ) as _i7.Future<_i6.BackupConfig>);
}
