// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/services/local_notification_service_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:horcrux/models/backup_config.dart' as _i5;
import 'package:horcrux/models/recovery_request.dart' as _i8;
import 'package:horcrux/models/share.dart' as _i7;
import 'package:horcrux/models/steward_status.dart' as _i6;
import 'package:horcrux/models/vault.dart' as _i4;
import 'package:horcrux/providers/vault_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultRepository extends _i1.Mock implements _i2.VaultRepository {
  MockVaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Vault>> get vaultsStream => (super.noSuchMethod(
        Invocation.getter(#vaultsStream),
        returnValue: _i3.Stream<List<_i4.Vault>>.empty(),
      ) as _i3.Stream<List<_i4.Vault>>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i4.Vault?> watchVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #watchVault,
          [id],
        ),
        returnValue: _i3.Stream<_i4.Vault?>.empty(),
      ) as _i3.Stream<_i4.Vault?>);

  @override
  _i3.Future<List<_i4.Vault>> getAllVaults() => (super.noSuchMethod(
        Invocation.method(
          #getAllVaults,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Vault>>.value(<_i4.Vault>[]),
      ) as _i3.Future<List<_i4.Vault>>);

  @override
  _i3.Future<_i4.Vault?> getVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getVault,
          [id],
        ),
        returnValue: _i3.Future<_i4.Vault?>.value(),
      ) as _i3.Future<_i4.Vault?>);

  @override
  _i3.Future<void> saveVault(_i4.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #saveVault,
          [vault],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addVault(_i4.Vault? vault) => (super.noSuchMethod(
        Invocation.method(
          #addVault,
          [vault],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateVault(
    String? id,
    String? name,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVault,
          [
            id,
            name,
            content,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setPushEnabled(
    String? vaultId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPushEnabled,
          [
            vaultId,
            enabled,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteVault(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVault,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateBackupConfig(
    String? vaultId,
    _i5.BackupConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [
            vaultId,
            config,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.BackupConfig?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i3.Future<_i5.BackupConfig?>.value(),
      ) as _i3.Future<_i5.BackupConfig?>);

  @override
  _i3.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i6.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    int? acknowledgedDistributionVersion,
    String? giftWrapEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
            #acknowledgedDistributionVersion: acknowledgedDistributionVersion,
            #giftWrapEventId: giftWrapEventId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isOwnedVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isOwnedVault,
          [vaultId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addShareToVault(
    String? vaultId,
    _i7.Share? share,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addShareToVault,
          [
            vaultId,
            share,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Share>> getSharesForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getSharesForVault,
          [vaultId],
        ),
        returnValue: _i3.Future<List<_i7.Share>>.value(<_i7.Share>[]),
      ) as _i3.Future<List<_i7.Share>>);

  @override
  _i3.Future<void> clearSharesForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #clearSharesForVault,
          [vaultId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertStewardRow({
    required String? id,
    required String? vaultId,
    required int? shareIndex,
    String? pubkey,
    String? name,
    bool? isOwner = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertStewardRow,
          [],
          {
            #id: id,
            #vaultId: vaultId,
            #shareIndex: shareIndex,
            #pubkey: pubkey,
            #name: name,
            #isOwner: isOwner,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> mergeVaultRowFromIncomingShare(
    String? vaultId,
    _i7.Share? share,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeVaultRowFromIncomingShare,
          [
            vaultId,
            share,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveOwnedVaultContent(
    String? vaultId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOwnedVaultContent,
          [
            vaultId,
            content,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteVaultContent(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVaultContent,
          [vaultId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isKeyHolderForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isKeyHolderForVault,
          [vaultId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addRecoveryRequestToVault(
    String? vaultId,
    _i8.RecoveryRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecoveryRequestToVault,
          [
            vaultId,
            request,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRecoveryRequestInVault(
    String? vaultId,
    String? requestId,
    _i8.RecoveryRequest? updatedRequest,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecoveryRequestInVault,
          [
            vaultId,
            requestId,
            updatedRequest,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.RecoveryRequest>> getRecoveryRequestsForVault(String? vaultId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryRequestsForVault,
          [vaultId],
        ),
        returnValue: _i3.Future<List<_i8.RecoveryRequest>>.value(<_i8.RecoveryRequest>[]),
      ) as _i3.Future<List<_i8.RecoveryRequest>>);

  @override
  _i3.Future<_i8.RecoveryRequest?> getActiveRecoveryRequest(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getActiveRecoveryRequest,
          [vaultId],
        ),
        returnValue: _i3.Future<_i8.RecoveryRequest?>.value(),
      ) as _i3.Future<_i8.RecoveryRequest?>);

  @override
  _i3.Future<List<_i8.RecoveryRequest>> getAllRecoveryRequests() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecoveryRequests,
          [],
        ),
        returnValue: _i3.Future<List<_i8.RecoveryRequest>>.value(<_i8.RecoveryRequest>[]),
      ) as _i3.Future<List<_i8.RecoveryRequest>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
