// Mocks generated by Mockito 5.4.4 from annotations
// in horcrux/test/services/recovery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:horcrux/models/backup_status.dart' as _i6;
import 'package:horcrux/models/event_status.dart' as _i15;
import 'package:horcrux/models/nostr_kinds.dart' as _i19;
import 'package:horcrux/models/recovery_request.dart' as _i12;
import 'package:horcrux/models/shard_data.dart' as _i9;
import 'package:horcrux/models/steward.dart' as _i7;
import 'package:horcrux/models/steward_status.dart' as _i10;
import 'package:horcrux/models/vault.dart' as _i18;
import 'package:horcrux/providers/vault_provider.dart' as _i3;
import 'package:horcrux/services/backup_service.dart' as _i4;
import 'package:horcrux/services/horcrux_notification_service.dart' as _i17;
import 'package:horcrux/services/local_notification_service.dart' as _i11;
import 'package:horcrux/services/ndk_service.dart' as _i13;
import 'package:horcrux/services/shard_distribution_service.dart' as _i14;
import 'package:horcrux/services/vault_share_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:ndk/ndk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdk_1 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVaultRepository_2 extends _i1.SmartFake implements _i3.VaultRepository {
  _FakeVaultRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNip01Event_3 extends _i1.SmartFake implements _i2.Nip01Event {
  _FakeNip01Event_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i4.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i6.BackupStatus status,
        List<_i7.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })> createBackupConfiguration({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i7.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
    String? contentHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackupConfiguration,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
            #contentHash: contentHash,
          },
        ),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i6.BackupStatus status,
              List<_i7.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(
              #createBackupConfiguration,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
                #contentHash: contentHash,
              },
            ),
          ),
          distributionVersion: 0,
          instructions: null,
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(
              #createBackupConfiguration,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
                #contentHash: contentHash,
              },
            ),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #createBackupConfiguration,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
                #contentHash: contentHash,
              },
            ),
          ),
          status: _i6.BackupStatus.pending,
          stewards: <_i7.Steward>[],
          threshold: 0,
          totalKeys: 0,
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #createBackupConfiguration,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
                #contentHash: contentHash,
              },
            ),
          )
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i6.BackupStatus status,
        List<_i7.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i6.BackupStatus status,
              List<_i7.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })?>.value(),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })?>);

  @override
  _i5.Future<
      List<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })>> getAllBackupConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getAllBackupConfigs,
          [],
        ),
        returnValue: _i5.Future<
            List<
                ({
                  String? contentHash,
                  DateTime createdAt,
                  int distributionVersion,
                  String? instructions,
                  DateTime? lastContentChange,
                  DateTime? lastRedistribution,
                  DateTime lastUpdated,
                  List<String> relays,
                  String specVersion,
                  _i6.BackupStatus status,
                  List<_i7.Steward> stewards,
                  int threshold,
                  int totalKeys,
                  String vaultId
                })>>.value(<({
          String? contentHash,
          DateTime createdAt,
          int distributionVersion,
          String? instructions,
          DateTime? lastContentChange,
          DateTime? lastRedistribution,
          DateTime lastUpdated,
          List<String> relays,
          String specVersion,
          _i6.BackupStatus status,
          List<_i7.Steward> stewards,
          int threshold,
          int totalKeys,
          String vaultId
        })>[]),
      ) as _i5.Future<
          List<
              ({
                String? contentHash,
                DateTime createdAt,
                int distributionVersion,
                String? instructions,
                DateTime? lastContentChange,
                DateTime? lastRedistribution,
                DateTime lastUpdated,
                List<String> relays,
                String specVersion,
                _i6.BackupStatus status,
                List<_i7.Steward> stewards,
                int threshold,
                int totalKeys,
                String vaultId
              })>>);

  @override
  _i5.Future<void> updateBackupConfig(
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [config],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBackupConfig,
          [vaultId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.ShardData>> generateShamirShares({
    required String? content,
    required int? threshold,
    required int? totalShards,
    required String? creatorPubkey,
    required String? vaultId,
    required String? vaultName,
    required List<Map<String, String>>? stewards,
    String? ownerName,
    String? instructions,
    bool? pushEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateShamirShares,
          [],
          {
            #content: content,
            #threshold: threshold,
            #totalShards: totalShards,
            #creatorPubkey: creatorPubkey,
            #vaultId: vaultId,
            #vaultName: vaultName,
            #stewards: stewards,
            #ownerName: ownerName,
            #instructions: instructions,
            #pushEnabled: pushEnabled,
          },
        ),
        returnValue: _i5.Future<List<_i9.ShardData>>.value(<_i9.ShardData>[]),
      ) as _i5.Future<List<_i9.ShardData>>);

  @override
  _i5.Future<String> reconstructFromShares({required List<_i9.ShardData>? shares}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconstructFromShares,
          [],
          {#shares: shares},
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #reconstructFromShares,
            [],
            {#shares: shares},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateBackupStatus(
    String? vaultId,
    _i6.BackupStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupStatus,
          [
            vaultId,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i10.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isBackupReady(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isBackupReady,
          [vaultId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i6.BackupStatus status,
        List<_i7.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })> mergeBackupConfig({
    required String? vaultId,
    int? threshold,
    List<_i7.Steward>? stewards,
    List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i6.BackupStatus status,
              List<_i7.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(
              #mergeBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          distributionVersion: 0,
          instructions: null,
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(
              #mergeBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #mergeBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          status: _i6.BackupStatus.pending,
          stewards: <_i7.Steward>[],
          threshold: 0,
          totalKeys: 0,
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #mergeBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          )
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })>);

  @override
  _i5.Future<void> handleContentChange(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #handleContentChange,
          [vaultId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> distributeKeysIfNecessary(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #distributeKeysIfNecessary,
          [vaultId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i6.BackupStatus status,
        List<_i7.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })> saveBackupConfig({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i7.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i6.BackupStatus status,
              List<_i7.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(
              #saveBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          distributionVersion: 0,
          instructions: null,
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(
              #saveBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #saveBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          ),
          status: _i6.BackupStatus.pending,
          stewards: <_i7.Steward>[],
          threshold: 0,
          totalKeys: 0,
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #saveBackupConfig,
              [],
              {
                #vaultId: vaultId,
                #threshold: threshold,
                #totalKeys: totalKeys,
                #stewards: stewards,
                #relays: relays,
                #instructions: instructions,
              },
            ),
          )
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })>);

  @override
  _i5.Future<
      ({
        String? contentHash,
        DateTime createdAt,
        int distributionVersion,
        String? instructions,
        DateTime? lastContentChange,
        DateTime? lastRedistribution,
        DateTime lastUpdated,
        List<String> relays,
        String specVersion,
        _i6.BackupStatus status,
        List<_i7.Steward> stewards,
        int threshold,
        int totalKeys,
        String vaultId
      })> createAndDistributeBackup({required String? vaultId}) => (super.noSuchMethod(
        Invocation.method(
          #createAndDistributeBackup,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i5.Future<
            ({
              String? contentHash,
              DateTime createdAt,
              int distributionVersion,
              String? instructions,
              DateTime? lastContentChange,
              DateTime? lastRedistribution,
              DateTime lastUpdated,
              List<String> relays,
              String specVersion,
              _i6.BackupStatus status,
              List<_i7.Steward> stewards,
              int threshold,
              int totalKeys,
              String vaultId
            })>.value((
          contentHash: null,
          createdAt: _FakeDateTime_0(
            this,
            Invocation.method(
              #createAndDistributeBackup,
              [],
              {#vaultId: vaultId},
            ),
          ),
          distributionVersion: 0,
          instructions: null,
          lastContentChange: null,
          lastRedistribution: null,
          lastUpdated: _FakeDateTime_0(
            this,
            Invocation.method(
              #createAndDistributeBackup,
              [],
              {#vaultId: vaultId},
            ),
          ),
          relays: <String>[],
          specVersion: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #createAndDistributeBackup,
              [],
              {#vaultId: vaultId},
            ),
          ),
          status: _i6.BackupStatus.pending,
          stewards: <_i7.Steward>[],
          threshold: 0,
          totalKeys: 0,
          vaultId: _i8.dummyValue<String>(
            this,
            Invocation.method(
              #createAndDistributeBackup,
              [],
              {#vaultId: vaultId},
            ),
          )
        )),
      ) as _i5.Future<
          ({
            String? contentHash,
            DateTime createdAt,
            int distributionVersion,
            String? instructions,
            DateTime? lastContentChange,
            DateTime? lastRedistribution,
            DateTime lastUpdated,
            List<String> relays,
            String specVersion,
            _i6.BackupStatus status,
            List<_i7.Steward> stewards,
            int threshold,
            int totalKeys,
            String vaultId
          })>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock implements _i11.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> notifyRecoveryRequestProcessed(_i12.RecoveryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyRecoveryRequestProcessed,
          [request],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> notifyRecoveryResponseProcessed(_i13.RecoveryResponseEvent? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyRecoveryResponseProcessed,
          [response],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> notifyShardDataProcessed({
    required _i2.Nip01Event? event,
    required _i9.ShardData? shardData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyShardDataProcessed,
          [],
          {
            #event: event,
            #shardData: shardData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> notifyShardConfirmationProcessed({
    required _i2.Nip01Event? event,
    required String? vaultId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyShardConfirmationProcessed,
          [],
          {
            #event: event,
            #vaultId: vaultId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> requestPlatformNotificationPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPlatformNotificationPermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> showNotification({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShardDistributionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShardDistributionService extends _i1.Mock implements _i14.ShardDistributionService {
  MockShardDistributionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<
      List<
          ({
            String backupConfigId,
            DateTime createdAt,
            String encryptedContent,
            String eventId,
            DateTime? publishedAt,
            String recipientPubkey,
            int shardIndex,
            _i15.EventStatus status
          })>> distributeShards({
    required String? ownerPubkey,
    required ({
      String? contentHash,
      DateTime createdAt,
      int distributionVersion,
      String? instructions,
      DateTime? lastContentChange,
      DateTime? lastRedistribution,
      DateTime lastUpdated,
      List<String> relays,
      String specVersion,
      _i6.BackupStatus status,
      List<_i7.Steward> stewards,
      int threshold,
      int totalKeys,
      String vaultId
    })? config,
    required List<_i9.ShardData>? shards,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributeShards,
          [],
          {
            #ownerPubkey: ownerPubkey,
            #config: config,
            #shards: shards,
          },
        ),
        returnValue: _i5.Future<
            List<
                ({
                  String backupConfigId,
                  DateTime createdAt,
                  String encryptedContent,
                  String eventId,
                  DateTime? publishedAt,
                  String recipientPubkey,
                  int shardIndex,
                  _i15.EventStatus status
                })>>.value(<({
          String backupConfigId,
          DateTime createdAt,
          String encryptedContent,
          String eventId,
          DateTime? publishedAt,
          String recipientPubkey,
          int shardIndex,
          _i15.EventStatus status
        })>[]),
      ) as _i5.Future<
          List<
              ({
                String backupConfigId,
                DateTime createdAt,
                String encryptedContent,
                String eventId,
                DateTime? publishedAt,
                String recipientPubkey,
                int shardIndex,
                _i15.EventStatus status
              })>>);

  @override
  _i5.Future<void> updateDistributionStatus({
    required String? vaultId,
    required List<
            ({
              String backupConfigId,
              DateTime createdAt,
              String encryptedContent,
              String eventId,
              DateTime? publishedAt,
              String recipientPubkey,
              int shardIndex,
              _i15.EventStatus status
            })>?
        shardEvents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDistributionStatus,
          [],
          {
            #vaultId: vaultId,
            #shardEvents: shardEvents,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processShardConfirmationEvent({required _i2.Nip01Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processShardConfirmationEvent,
          [],
          {#event: event},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processShardErrorEvent({required _i2.Nip01Event? event}) => (super.noSuchMethod(
        Invocation.method(
          #processShardErrorEvent,
          [],
          {#event: event},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i13.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i12.RecoveryRequest> get recoveryRequestStream => (super.noSuchMethod(
        Invocation.getter(#recoveryRequestStream),
        returnValue: _i5.Stream<_i12.RecoveryRequest>.empty(),
      ) as _i5.Stream<_i12.RecoveryRequest>);

  @override
  _i5.Stream<_i13.RecoveryResponseEvent> get recoveryResponseStream => (super.noSuchMethod(
        Invocation.getter(#recoveryResponseStream),
        returnValue: _i5.Stream<_i13.RecoveryResponseEvent>.empty(),
      ) as _i5.Stream<_i13.RecoveryResponseEvent>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processGiftWrapFromForegroundPush(_i2.Nip01Event? event) => (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i5.Future<_i2.Nip01Event?>.value(),
      ) as _i5.Future<_i2.Nip01Event?>);

  @override
  _i5.Future<String?> resolveVaultIdForGiftWrap(_i2.Nip01Event? giftWrap) => (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishRecoveryRequest({
    required String? vaultId,
    required List<String>? stewardPubkeys,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishRecoveryRequest,
          [],
          {
            #vaultId: vaultId,
            #stewardPubkeys: stewardPubkeys,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishRecoveryResponse({
    required String? initiatorPubkey,
    required String? recoveryRequestId,
    required bool? approved,
    String? shardDataJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishRecoveryResponse,
          [],
          {
            #initiatorPubkey: initiatorPubkey,
            #recoveryRequestId: recoveryRequestId,
            #approved: approved,
            #shardDataJson: shardDataJson,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i2.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
          },
        ),
        returnValue: _i5.Future<_i2.Nip01Event?>.value(),
      ) as _i5.Future<_i2.Nip01Event?>);

  @override
  _i5.Future<List<_i2.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
          },
        ),
        returnValue: _i5.Future<List<_i2.Nip01Event?>>.value(<_i2.Nip01Event?>[]),
      ) as _i5.Future<List<_i2.Nip01Event?>>);

  @override
  _i5.Future<_i2.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i5.Future<_i2.Ndk>.value(_FakeNdk_1(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Ndk>);

  @override
  void setNdkForTesting(_i2.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [VaultShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultShareService extends _i1.Mock implements _i16.VaultShareService {
  MockVaultShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VaultRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeVaultRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.VaultRepository);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.ShardData>> getVaultShares(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getVaultShares,
          [vaultId],
        ),
        returnValue: _i5.Future<List<_i9.ShardData>>.value(<_i9.ShardData>[]),
      ) as _i5.Future<List<_i9.ShardData>>);

  @override
  _i5.Future<_i9.ShardData?> getVaultShare(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getVaultShare,
          [vaultId],
        ),
        returnValue: _i5.Future<_i9.ShardData?>.value(),
      ) as _i5.Future<_i9.ShardData?>);

  @override
  _i5.Future<_i9.ShardData?> getShareByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(
          #getShareByEventId,
          [nostrEventId],
        ),
        returnValue: _i5.Future<_i9.ShardData?>.value(),
      ) as _i5.Future<_i9.ShardData?>);

  @override
  _i5.Future<void> addVaultShare(
    String? vaultId,
    _i9.ShardData? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVaultShare,
          [
            vaultId,
            shardData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processVaultShare(
    String? vaultId,
    _i9.ShardData? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processVaultShare,
          [
            vaultId,
            shardData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> sendShardConfirmationEvent({
    required String? vaultId,
    required int? shardIndex,
    required String? ownerPubkey,
    required List<String>? relayUrls,
    int? distributionVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendShardConfirmationEvent,
          [],
          {
            #vaultId: vaultId,
            #shardIndex: shardIndex,
            #ownerPubkey: ownerPubkey,
            #relayUrls: relayUrls,
            #distributionVersion: distributionVersion,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> markShareAsReceived(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #markShareAsReceived,
          [vaultId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markShareAsReceivedByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(
          #markShareAsReceivedByEventId,
          [nostrEventId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> reassembleVaultContent(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #reassembleVaultContent,
          [vaultId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasShard(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #hasShard,
          [vaultId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i9.ShardData>> getAllCollectedShards() => (super.noSuchMethod(
        Invocation.method(
          #getAllCollectedShards,
          [],
        ),
        returnValue: _i5.Future<List<_i9.ShardData>>.value(<_i9.ShardData>[]),
      ) as _i5.Future<List<_i9.ShardData>>);

  @override
  _i5.Future<List<String>> getVaultsWithShares() => (super.noSuchMethod(
        Invocation.method(
          #getVaultsWithShares,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> isKeyHolderForVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isKeyHolderForVault,
          [vaultId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getShardCount(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getShardCount,
          [vaultId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> removeVaultShare(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #removeVaultShare,
          [vaultId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeShareByEventId(String? nostrEventId) => (super.noSuchMethod(
        Invocation.method(
          #removeShareByEventId,
          [nostrEventId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTotalShardCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalShardCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> addRecoveryShard(
    String? recoveryRequestId,
    _i9.ShardData? shardData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecoveryShard,
          [
            recoveryRequestId,
            shardData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.ShardData>> getRecoveryShards(String? recoveryRequestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryShards,
          [recoveryRequestId],
        ),
        returnValue: _i5.Future<List<_i9.ShardData>>.value(<_i9.ShardData>[]),
      ) as _i5.Future<List<_i9.ShardData>>);

  @override
  _i5.Future<int> getRecoveryShardCount(String? recoveryRequestId) => (super.noSuchMethod(
        Invocation.method(
          #getRecoveryShardCount,
          [recoveryRequestId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> hasSufficientRecoveryShards(
    String? recoveryRequestId,
    int? threshold,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasSufficientRecoveryShards,
          [
            recoveryRequestId,
            threshold,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> removeRecoveryShards(String? recoveryRequestId) => (super.noSuchMethod(
        Invocation.method(
          #removeRecoveryShards,
          [recoveryRequestId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processKeyHolderRemoval({required _i2.Nip01Event? event}) => (super.noSuchMethod(
        Invocation.method(
          #processKeyHolderRemoval,
          [],
          {#event: event},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [HorcruxNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorcruxNotificationService extends _i1.Mock implements _i17.HorcruxNotificationService {
  MockHorcruxNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setBaseUrl(String? override) => (super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [override],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> register({
    required String? fcmToken,
    required _i17.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fcmToken: fcmToken,
            #platform: platform,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deregister() => (super.noSuchMethod(
        Invocation.method(
          #deregister,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateToken({
    required String? newToken,
    required _i17.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [],
          {
            #newToken: newToken,
            #platform: platform,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceConsents(List<String>? authorizedSenders) => (super.noSuchMethod(
        Invocation.method(
          #replaceConsents,
          [authorizedSenders],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> computeConsentList({
    required String? currentUserPubkey,
    required List<_i18.Vault>? vaults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeConsentList,
          [],
          {
            #currentUserPubkey: currentUserPubkey,
            #vaults: vaults,
          },
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<void> syncConsentList() => (super.noSuchMethod(
        Invocation.method(
          #syncConsentList,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteConsent(String? senderPubkey) => (super.noSuchMethod(
        Invocation.method(
          #deleteConsent,
          [senderPubkey],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> tryPushForEvent({
    required _i2.Nip01Event? event,
    required _i19.NostrKind? kind,
    required _i18.Vault? vault,
    List<String>? relayHints,
    bool? recoveryApproved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryPushForEvent,
          [],
          {
            #event: event,
            #kind: kind,
            #vault: vault,
            #relayHints: relayHints,
            #recoveryApproved: recoveryApproved,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> push({
    required String? recipientPubkey,
    required String? title,
    required String? body,
    Map<String, dynamic>? eventJson,
    String? eventId,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [],
          {
            #recipientPubkey: recipientPubkey,
            #title: title,
            #body: body,
            #eventJson: eventJson,
            #eventId: eventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Nip01Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockNip01Event extends _i1.Mock implements _i2.Nip01Event {
  MockNip01Event() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get pubKey => (super.noSuchMethod(
        Invocation.getter(#pubKey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#pubKey),
        ),
      ) as String);

  @override
  int get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: 0,
      ) as int);

  @override
  set createdAt(int? _createdAt) => super.noSuchMethod(
        Invocation.setter(
          #createdAt,
          _createdAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: 0,
      ) as int);

  @override
  List<List<String>> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <List<String>>[],
      ) as List<List<String>>);

  @override
  set tags(List<List<String>>? _tags) => super.noSuchMethod(
        Invocation.setter(
          #tags,
          _tags,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#content),
        ),
      ) as String);

  @override
  set content(String? _content) => super.noSuchMethod(
        Invocation.setter(
          #content,
          _content,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get sig => (super.noSuchMethod(
        Invocation.getter(#sig),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sig),
        ),
      ) as String);

  @override
  set sig(String? _sig) => super.noSuchMethod(
        Invocation.setter(
          #sig,
          _sig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set validSig(bool? _validSig) => super.noSuchMethod(
        Invocation.setter(
          #validSig,
          _validSig,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get sources => (super.noSuchMethod(
        Invocation.getter(#sources),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set sources(List<String>? _sources) => super.noSuchMethod(
        Invocation.setter(
          #sources,
          _sources,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isIdValid => (super.noSuchMethod(
        Invocation.getter(#isIdValid),
        returnValue: false,
      ) as bool);

  @override
  List<String> get tTags => (super.noSuchMethod(
        Invocation.getter(#tTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get pTags => (super.noSuchMethod(
        Invocation.getter(#pTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get replyETags => (super.noSuchMethod(
        Invocation.getter(#replyETags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String toBase64() => (super.noSuchMethod(
        Invocation.method(
          #toBase64,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toBase64,
            [],
          ),
        ),
      ) as String);

  @override
  void sign(String? privateKey) => super.noSuchMethod(
        Invocation.method(
          #sign,
          [privateKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getTags(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [tag],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String? getFirstTag(String? name) => (super.noSuchMethod(Invocation.method(
        #getFirstTag,
        [name],
      )) as String?);

  @override
  _i2.Nip01Event copyWith({
    String? pubKey,
    int? createdAt,
    int? kind,
    List<List<String>>? tags,
    String? content,
    String? sig,
    List<String>? sources,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #pubKey: pubKey,
            #createdAt: createdAt,
            #kind: kind,
            #tags: tags,
            #content: content,
            #sig: sig,
            #sources: sources,
          },
        ),
        returnValue: _FakeNip01Event_3(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #pubKey: pubKey,
              #createdAt: createdAt,
              #kind: kind,
              #tags: tags,
              #content: content,
              #sig: sig,
              #sources: sources,
            },
          ),
        ),
      ) as _i2.Nip01Event);
}
