// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/services/recovery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:horcrux/models/backup_config.dart' as _i2;
import 'package:horcrux/models/backup_status.dart' as _i11;
import 'package:horcrux/models/event_status.dart' as _i17;
import 'package:horcrux/models/nostr_kinds.dart' as _i15;
import 'package:horcrux/models/recovery_request.dart' as _i14;
import 'package:horcrux/models/relay_configuration.dart' as _i22;
import 'package:horcrux/models/share.dart' as _i9;
import 'package:horcrux/models/steward.dart' as _i8;
import 'package:horcrux/models/steward_status.dart' as _i12;
import 'package:horcrux/models/vault.dart' as _i19;
import 'package:horcrux/models/vault_detail.dart' as _i21;
import 'package:horcrux/providers/vault_detail_repository.dart' as _i20;
import 'package:horcrux/services/backup_service.dart' as _i6;
import 'package:horcrux/services/horcrux_notification_service.dart' as _i18;
import 'package:horcrux/services/local_notification_service.dart' as _i13;
import 'package:horcrux/services/ndk_service.dart' as _i4;
import 'package:horcrux/services/relay_scan_service.dart' as _i5;
import 'package:horcrux/services/share_distribution_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:ndk/ndk.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBackupConfig_0 extends _i1.SmartFake implements _i2.BackupConfig {
  _FakeBackupConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdk_1 extends _i1.SmartFake implements _i3.Ndk {
  _FakeNdk_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNip01Event_2 extends _i1.SmartFake implements _i3.Nip01Event {
  _FakeNip01Event_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdkService_3 extends _i1.SmartFake implements _i4.NdkService {
  _FakeNdkService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanningStatus_4 extends _i1.SmartFake implements _i5.ScanningStatus {
  _FakeScanningStatus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i6.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.BackupConfig> createBackupConfiguration({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i8.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackupConfiguration,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i2.BackupConfig>.value(_FakeBackupConfig_0(
          this,
          Invocation.method(
            #createBackupConfiguration,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i2.BackupConfig>);

  @override
  _i7.Future<_i2.BackupConfig?> getBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getBackupConfig,
          [vaultId],
        ),
        returnValue: _i7.Future<_i2.BackupConfig?>.value(),
      ) as _i7.Future<_i2.BackupConfig?>);

  @override
  _i7.Future<List<_i2.BackupConfig>> getAllBackupConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getAllBackupConfigs,
          [],
        ),
        returnValue: _i7.Future<List<_i2.BackupConfig>>.value(<_i2.BackupConfig>[]),
      ) as _i7.Future<List<_i2.BackupConfig>>);

  @override
  _i7.Future<void> updateBackupConfig(_i2.BackupConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #updateBackupConfig,
          [config],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBackupConfig(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBackupConfig,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.Share>> generateShamirShares({
    required String? content,
    required int? threshold,
    required int? totalShards,
    required String? creatorPubkey,
    required String? vaultId,
    required String? vaultName,
    required List<Map<String, String>>? stewards,
    String? ownerName,
    String? instructions,
    bool? pushEnabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateShamirShares,
          [],
          {
            #content: content,
            #threshold: threshold,
            #totalShards: totalShards,
            #creatorPubkey: creatorPubkey,
            #vaultId: vaultId,
            #vaultName: vaultName,
            #stewards: stewards,
            #ownerName: ownerName,
            #instructions: instructions,
            #pushEnabled: pushEnabled,
          },
        ),
        returnValue: _i7.Future<List<_i9.Share>>.value(<_i9.Share>[]),
      ) as _i7.Future<List<_i9.Share>>);

  @override
  _i7.Future<String> reconstructFromShares({required List<_i9.Share>? shares}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconstructFromShares,
          [],
          {#shares: shares},
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #reconstructFromShares,
            [],
            {#shares: shares},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateBackupStatus(
    String? vaultId,
    _i11.BackupStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupStatus,
          [
            vaultId,
            status,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateStewardStatus({
    required String? vaultId,
    required String? pubkey,
    required _i12.StewardStatus? status,
    DateTime? acknowledgedAt,
    String? acknowledgmentEventId,
    String? giftWrapEventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStewardStatus,
          [],
          {
            #vaultId: vaultId,
            #pubkey: pubkey,
            #status: status,
            #acknowledgedAt: acknowledgedAt,
            #acknowledgmentEventId: acknowledgmentEventId,
            #giftWrapEventId: giftWrapEventId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isBackupReady(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #isBackupReady,
          [vaultId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.BackupConfig> mergeBackupConfig({
    required String? vaultId,
    int? threshold,
    List<_i8.Steward>? stewards,
    List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i2.BackupConfig>.value(_FakeBackupConfig_0(
          this,
          Invocation.method(
            #mergeBackupConfig,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i2.BackupConfig>);

  @override
  _i7.Future<void> handleContentChange(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #handleContentChange,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> redistributeKeys({required String? vaultId}) => (super.noSuchMethod(
        Invocation.method(
          #redistributeKeys,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> redistributeForPushPreferenceChange({required String? vaultId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #redistributeForPushPreferenceChange,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> distributeKeysIfNecessary(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #distributeKeysIfNecessary,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.BackupConfig> saveBackupConfig({
    required String? vaultId,
    required int? threshold,
    required int? totalKeys,
    required List<_i8.Steward>? stewards,
    required List<String>? relays,
    String? instructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBackupConfig,
          [],
          {
            #vaultId: vaultId,
            #threshold: threshold,
            #totalKeys: totalKeys,
            #stewards: stewards,
            #relays: relays,
            #instructions: instructions,
          },
        ),
        returnValue: _i7.Future<_i2.BackupConfig>.value(_FakeBackupConfig_0(
          this,
          Invocation.method(
            #saveBackupConfig,
            [],
            {
              #vaultId: vaultId,
              #threshold: threshold,
              #totalKeys: totalKeys,
              #stewards: stewards,
              #relays: relays,
              #instructions: instructions,
            },
          ),
        )),
      ) as _i7.Future<_i2.BackupConfig>);

  @override
  _i7.Future<_i2.BackupConfig> createAndDistributeBackup({required String? vaultId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAndDistributeBackup,
          [],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<_i2.BackupConfig>.value(_FakeBackupConfig_0(
          this,
          Invocation.method(
            #createAndDistributeBackup,
            [],
            {#vaultId: vaultId},
          ),
        )),
      ) as _i7.Future<_i2.BackupConfig>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock implements _i13.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> notifyRecoveryRequestProcessed(_i14.RecoveryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyRecoveryRequestProcessed,
          [request],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> notifyRecoveryResponseProcessed(_i4.RecoveryResponseEvent? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyRecoveryResponseProcessed,
          [response],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> notifyShareDataProcessed({
    required _i3.Nip01Event? event,
    required _i9.Share? share,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyShareDataProcessed,
          [],
          {
            #event: event,
            #share: share,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> notifyShareConfirmationProcessed({
    required _i3.Nip01Event? event,
    required String? vaultId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyShareConfirmationProcessed,
          [],
          {
            #event: event,
            #vaultId: vaultId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> requestPlatformNotificationPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPlatformNotificationPermissions,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> areOsNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #areOsNotificationsEnabled,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> showNotification({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> navigateForKind(
    _i15.NostrKind? kind,
    String? id, {
    String? vaultId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateForKind,
          [
            kind,
            id,
          ],
          {#vaultId: vaultId},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> navigateToVault(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #navigateToVault,
          [vaultId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShareDistributionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareDistributionService extends _i1.Mock implements _i16.ShareDistributionService {
  MockShareDistributionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<
      List<
          ({
            DateTime createdAt,
            String giftWrapEventId,
            DateTime? publishedAt,
            String recipientPubkey,
            int shareIndex,
            _i17.EventStatus status
          })>> distributeShares({
    required String? ownerPubkey,
    required _i2.BackupConfig? config,
    required List<_i9.Share>? shares,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributeShares,
          [],
          {
            #ownerPubkey: ownerPubkey,
            #config: config,
            #shares: shares,
          },
        ),
        returnValue: _i7.Future<
            List<
                ({
                  DateTime createdAt,
                  String giftWrapEventId,
                  DateTime? publishedAt,
                  String recipientPubkey,
                  int shareIndex,
                  _i17.EventStatus status
                })>>.value(<({
          DateTime createdAt,
          String giftWrapEventId,
          DateTime? publishedAt,
          String recipientPubkey,
          int shareIndex,
          _i17.EventStatus status
        })>[]),
      ) as _i7.Future<
          List<
              ({
                DateTime createdAt,
                String giftWrapEventId,
                DateTime? publishedAt,
                String recipientPubkey,
                int shareIndex,
                _i17.EventStatus status
              })>>);

  @override
  _i7.Future<void> updateDistributionStatus({
    required String? vaultId,
    required List<
            ({
              DateTime createdAt,
              String giftWrapEventId,
              DateTime? publishedAt,
              String recipientPubkey,
              int shareIndex,
              _i17.EventStatus status
            })>?
        shareEvents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDistributionStatus,
          [],
          {
            #vaultId: vaultId,
            #shareEvents: shareEvents,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processShareConfirmationEvent({required _i3.Nip01Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #processShareConfirmationEvent,
          [],
          {#event: event},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processShareErrorEvent({required _i3.Nip01Event? event}) => (super.noSuchMethod(
        Invocation.method(
          #processShareErrorEvent,
          [],
          {#event: event},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i4.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setActiveRelays(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #setActiveRelays,
          [relayUrls],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> processGiftWrapFromForegroundPush(
    _i3.Nip01Event? event, {
    bool? allowLocalNotification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
          {#allowLocalNotification: allowLocalNotification},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i7.Future<_i3.Nip01Event?>.value(),
      ) as _i7.Future<_i3.Nip01Event?>);

  @override
  _i7.Future<_i9.Share?> loadShareDataFromPublishedDistributionGiftWrap({
    required String? giftWrapEventId,
    required List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadShareDataFromPublishedDistributionGiftWrap,
          [],
          {
            #giftWrapEventId: giftWrapEventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i7.Future<_i9.Share?>.value(),
      ) as _i7.Future<_i9.Share?>);

  @override
  _i7.Future<String?> resolveVaultIdForGiftWrap(_i3.Nip01Event? giftWrap) => (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<({_i15.NostrKind kind, String recoveryRequestId})?>
      resolveRecoveryRequestIdForGiftWrap(_i3.Nip01Event? giftWrap) => (super.noSuchMethod(
            Invocation.method(
              #resolveRecoveryRequestIdForGiftWrap,
              [giftWrap],
            ),
            returnValue: _i7.Future<({_i15.NostrKind kind, String recoveryRequestId})?>.value(),
          ) as _i7.Future<({_i15.NostrKind kind, String recoveryRequestId})?>);

  @override
  _i7.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> queryHistoricalGiftWraps({required List<String>? relayUrls}) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryHistoricalGiftWraps,
          [],
          {#relayUrls: relayUrls},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<_i3.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i7.Future<_i3.Nip01Event?>.value(),
      ) as _i7.Future<_i3.Nip01Event?>);

  @override
  _i7.Future<List<_i3.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
    String? vaultId,
    Duration? nip40Expiration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
            #vaultId: vaultId,
            #nip40Expiration: nip40Expiration,
          },
        ),
        returnValue: _i7.Future<List<_i3.Nip01Event?>>.value(<_i3.Nip01Event?>[]),
      ) as _i7.Future<List<_i3.Nip01Event?>>);

  @override
  _i7.Future<_i3.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i7.Future<_i3.Ndk>.value(_FakeNdk_1(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Ndk>);

  @override
  void setNdkForTesting(_i3.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disposePublishWorkerSync() => super.noSuchMethod(
        Invocation.method(
          #disposePublishWorkerSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [HorcruxNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorcruxNotificationService extends _i1.Mock implements _i18.HorcruxNotificationService {
  MockHorcruxNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> setBaseUrl(String? override) => (super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [override],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> register({
    required String? fcmToken,
    required _i18.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fcmToken: fcmToken,
            #platform: platform,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deregister() => (super.noSuchMethod(
        Invocation.method(
          #deregister,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateToken({
    required String? newToken,
    required _i18.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [],
          {
            #newToken: newToken,
            #platform: platform,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> replaceConsents(List<String>? authorizedSenders) => (super.noSuchMethod(
        Invocation.method(
          #replaceConsents,
          [authorizedSenders],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<String> computeConsentList({
    required String? currentUserPubkey,
    required List<_i19.Vault>? vaults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeConsentList,
          [],
          {
            #currentUserPubkey: currentUserPubkey,
            #vaults: vaults,
          },
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> syncConsentList() => (super.noSuchMethod(
        Invocation.method(
          #syncConsentList,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteConsent(String? senderPubkey) => (super.noSuchMethod(
        Invocation.method(
          #deleteConsent,
          [senderPubkey],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> tryPushForEvent({
    required _i3.Nip01Event? event,
    required _i15.NostrKind? kind,
    required _i19.Vault? vault,
    List<String>? relayHints,
    bool? recoveryApproved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryPushForEvent,
          [],
          {
            #event: event,
            #kind: kind,
            #vault: vault,
            #relayHints: relayHints,
            #recoveryApproved: recoveryApproved,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> push({
    required String? recipientPubkey,
    required String? title,
    required String? body,
    Map<String, dynamic>? eventJson,
    String? eventId,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [],
          {
            #recipientPubkey: recipientPubkey,
            #title: title,
            #body: body,
            #eventJson: eventJson,
            #eventId: eventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Nip01Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockNip01Event extends _i1.Mock implements _i3.Nip01Event {
  MockNip01Event() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get pubKey => (super.noSuchMethod(
        Invocation.getter(#pubKey),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#pubKey),
        ),
      ) as String);

  @override
  int get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: 0,
      ) as int);

  @override
  int get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: 0,
      ) as int);

  @override
  List<List<String>> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <List<String>>[],
      ) as List<List<String>>);

  @override
  String get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#content),
        ),
      ) as String);

  @override
  List<String> get sources => (super.noSuchMethod(
        Invocation.getter(#sources),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get tTags => (super.noSuchMethod(
        Invocation.getter(#tTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get pTags => (super.noSuchMethod(
        Invocation.getter(#pTags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get replyETags => (super.noSuchMethod(
        Invocation.getter(#replyETags),
        returnValue: <String>[],
      ) as List<String>);

  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set createdAt(int? _createdAt) => super.noSuchMethod(
        Invocation.setter(
          #createdAt,
          _createdAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Nip01Event copyWith({
    String? id,
    String? pubKey,
    int? createdAt,
    int? kind,
    List<List<String>>? tags,
    String? content,
    String? sig,
    bool? validSig,
    List<String>? sources,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #pubKey: pubKey,
            #createdAt: createdAt,
            #kind: kind,
            #tags: tags,
            #content: content,
            #sig: sig,
            #validSig: validSig,
            #sources: sources,
          },
        ),
        returnValue: _FakeNip01Event_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #pubKey: pubKey,
              #createdAt: createdAt,
              #kind: kind,
              #tags: tags,
              #content: content,
              #sig: sig,
              #validSig: validSig,
              #sources: sources,
            },
          ),
        ),
      ) as _i3.Nip01Event);

  @override
  List<String> getTags(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [tag],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String? getFirstTag(String? name) => (super.noSuchMethod(Invocation.method(
        #getFirstTag,
        [name],
      )) as String?);
}

/// A class which mocks [VaultDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultDetailRepository extends _i1.Mock implements _i20.VaultDetailRepository {
  MockVaultDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i21.VaultDetail>> get vaultListStream => (super.noSuchMethod(
        Invocation.getter(#vaultListStream),
        returnValue: _i7.Stream<List<_i21.VaultDetail>>.empty(),
      ) as _i7.Stream<List<_i21.VaultDetail>>);

  @override
  _i7.Stream<_i21.VaultDetail?> watchVaultDetail(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #watchVaultDetail,
          [vaultId],
        ),
        returnValue: _i7.Stream<_i21.VaultDetail?>.empty(),
      ) as _i7.Stream<_i21.VaultDetail?>);

  @override
  _i7.Future<_i21.VaultDetail?> getVaultDetail(String? vaultId) => (super.noSuchMethod(
        Invocation.method(
          #getVaultDetail,
          [vaultId],
        ),
        returnValue: _i7.Future<_i21.VaultDetail?>.value(),
      ) as _i7.Future<_i21.VaultDetail?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RelayScanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayScanService extends _i1.Mock implements _i5.RelayScanService {
  MockRelayScanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NdkService get ndkService => (super.noSuchMethod(
        Invocation.getter(#ndkService),
        returnValue: _FakeNdkService_3(
          this,
          Invocation.getter(#ndkService),
        ),
      ) as _i4.NdkService);

  @override
  void disposeSync() => super.noSuchMethod(
        Invocation.method(
          #disposeSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i22.RelayConfiguration>> getRelayConfigurations({bool? enabledOnly}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfigurations,
          [],
          {#enabledOnly: enabledOnly},
        ),
        returnValue: _i7.Future<List<_i22.RelayConfiguration>>.value(<_i22.RelayConfiguration>[]),
      ) as _i7.Future<List<_i22.RelayConfiguration>>);

  @override
  _i7.Future<_i22.RelayConfiguration?> getRelayConfiguration(String? relayId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelayConfiguration,
          [relayId],
        ),
        returnValue: _i7.Future<_i22.RelayConfiguration?>.value(),
      ) as _i7.Future<_i22.RelayConfiguration?>);

  @override
  _i7.Future<void> addRelayConfiguration(_i22.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #addRelayConfiguration,
          [relay],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateRelayConfiguration(_i22.RelayConfiguration? relay) => (super.noSuchMethod(
        Invocation.method(
          #updateRelayConfiguration,
          [relay],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeRelayConfiguration(String? relayId) => (super.noSuchMethod(
        Invocation.method(
          #removeRelayConfiguration,
          [relayId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> startRelayScanning({Duration? scanInterval}) => (super.noSuchMethod(
        Invocation.method(
          #startRelayScanning,
          [],
          {#scanInterval: scanInterval},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopRelayScanning() => (super.noSuchMethod(
        Invocation.method(
          #stopRelayScanning,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isScanningActive() => (super.noSuchMethod(
        Invocation.method(
          #isScanningActive,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i5.ScanningStatus> getScanningStatus() => (super.noSuchMethod(
        Invocation.method(
          #getScanningStatus,
          [],
        ),
        returnValue: _i7.Future<_i5.ScanningStatus>.value(_FakeScanningStatus_4(
          this,
          Invocation.method(
            #getScanningStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i5.ScanningStatus>);

  @override
  _i7.Future<void> scanNow() => (super.noSuchMethod(
        Invocation.method(
          #scanNow,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> syncRelaysFromUrls(List<String>? relayUrls) => (super.noSuchMethod(
        Invocation.method(
          #syncRelaysFromUrls,
          [relayUrls],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> ensureScanningStarted() => (super.noSuchMethod(
        Invocation.method(
          #ensureScanningStarted,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
