// Mocks generated by Mockito 5.4.4 from annotations
// in horcrux/test/services/vault_share_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:horcrux/models/nostr_kinds.dart' as _i11;
import 'package:horcrux/models/recovery_request.dart' as _i8;
import 'package:horcrux/models/vault.dart' as _i10;
import 'package:horcrux/services/horcrux_notification_service.dart' as _i9;
import 'package:horcrux/services/login_service.dart' as _i4;
import 'package:horcrux/services/ndk_service.dart' as _i7;
import 'package:horcrux/services/push_notification_receiver.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:ndk/ndk.dart' as _i3;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyPair_0 extends _i1.SmartFake implements _i2.KeyPair {
  _FakeKeyPair_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNdk_1 extends _i1.SmartFake implements _i3.Ndk {
  _FakeNdk_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i4.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.KeyPair> generateAndStoreNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #generateAndStoreNostrKey,
          [],
        ),
        returnValue: _i5.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #generateAndStoreNostrKey,
            [],
          ),
        )),
      ) as _i5.Future<_i2.KeyPair>);

  @override
  _i5.Future<_i2.KeyPair> importNsecKey(String? nsec) => (super.noSuchMethod(
        Invocation.method(
          #importNsecKey,
          [nsec],
        ),
        returnValue: _i5.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #importNsecKey,
            [nsec],
          ),
        )),
      ) as _i5.Future<_i2.KeyPair>);

  @override
  _i5.Future<_i2.KeyPair> importHexPrivateKey(String? hexPrivateKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #importHexPrivateKey,
          [hexPrivateKey],
        ),
        returnValue: _i5.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #importHexPrivateKey,
            [hexPrivateKey],
          ),
        )),
      ) as _i5.Future<_i2.KeyPair>);

  @override
  _i5.Future<_i2.KeyPair?> getStoredNostrKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredNostrKey,
          [],
        ),
        returnValue: _i5.Future<_i2.KeyPair?>.value(),
      ) as _i5.Future<_i2.KeyPair?>);

  @override
  _i5.Future<_i2.KeyPair> initializeKey() => (super.noSuchMethod(
        Invocation.method(
          #initializeKey,
          [],
        ),
        returnValue: _i5.Future<_i2.KeyPair>.value(_FakeKeyPair_0(
          this,
          Invocation.method(
            #initializeKey,
            [],
          ),
        )),
      ) as _i5.Future<_i2.KeyPair>);

  @override
  _i5.Future<String?> getCurrentPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKey,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getCurrentPublicKeyBech32() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPublicKeyBech32,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String> encryptText(String? plaintext) => (super.noSuchMethod(
        Invocation.method(
          #encryptText,
          [plaintext],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #encryptText,
            [plaintext],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> decryptText(String? encryptedText) => (super.noSuchMethod(
        Invocation.method(
          #decryptText,
          [encryptedText],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decryptText,
            [encryptedText],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> clearStoredKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearStoredKeys,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void resetCacheForTest() => super.noSuchMethod(
        Invocation.method(
          #resetCacheForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? npubToHex(String? npub) => (super.noSuchMethod(Invocation.method(
        #npubToHex,
        [npub],
      )) as String?);

  @override
  _i5.Future<String> encryptForRecipient({
    required String? plaintext,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptForRecipient,
          [],
          {
            #plaintext: plaintext,
            #recipientPubkey: recipientPubkey,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #encryptForRecipient,
            [],
            {
              #plaintext: plaintext,
              #recipientPubkey: recipientPubkey,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> decryptFromSender({
    required String? encryptedText,
    required String? senderPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFromSender,
          [],
          {
            #encryptedText: encryptedText,
            #senderPubkey: senderPubkey,
          },
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decryptFromSender,
            [],
            {
              #encryptedText: encryptedText,
              #senderPubkey: senderPubkey,
            },
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [NdkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNdkService extends _i1.Mock implements _i7.NdkService {
  MockNdkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.RecoveryRequest> get recoveryRequestStream =>
      (super.noSuchMethod(
        Invocation.getter(#recoveryRequestStream),
        returnValue: _i5.Stream<_i8.RecoveryRequest>.empty(),
      ) as _i5.Stream<_i8.RecoveryRequest>);

  @override
  _i5.Stream<_i7.RecoveryResponseEvent> get recoveryResponseStream =>
      (super.noSuchMethod(
        Invocation.getter(#recoveryResponseStream),
        returnValue: _i5.Stream<_i7.RecoveryResponseEvent>.empty(),
      ) as _i5.Stream<_i7.RecoveryResponseEvent>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> processGiftWrapFromForegroundPush(_i3.Nip01Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGiftWrapFromForegroundPush,
          [event],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Nip01Event?> fetchGiftWrapByIdForPush({
    required String? eventIdHex,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGiftWrapByIdForPush,
          [],
          {
            #eventIdHex: eventIdHex,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i5.Future<_i3.Nip01Event?>.value(),
      ) as _i5.Future<_i3.Nip01Event?>);

  @override
  _i5.Future<String?> resolveVaultIdForGiftWrap(_i3.Nip01Event? giftWrap) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveVaultIdForGiftWrap,
          [giftWrap],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishRecoveryRequest({
    required String? vaultId,
    required List<String>? stewardPubkeys,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishRecoveryRequest,
          [],
          {
            #vaultId: vaultId,
            #stewardPubkeys: stewardPubkeys,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> publishRecoveryResponse({
    required String? initiatorPubkey,
    required String? recoveryRequestId,
    required bool? approved,
    String? shardDataJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishRecoveryResponse,
          [],
          {
            #initiatorPubkey: initiatorPubkey,
            #recoveryRequestId: recoveryRequestId,
            #approved: approved,
            #shardDataJson: shardDataJson,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> closeSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getActiveRelays() => (super.noSuchMethod(
        Invocation.method(
          #getActiveRelays,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<String?> getCurrentPubkey() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPubkey,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.Nip01Event?> publishEncryptedEvent({
    required String? content,
    required int? kind,
    required String? recipientPubkey,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEvent,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkey: recipientPubkey,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
          },
        ),
        returnValue: _i5.Future<_i3.Nip01Event?>.value(),
      ) as _i5.Future<_i3.Nip01Event?>);

  @override
  _i5.Future<List<_i3.Nip01Event?>> publishEncryptedEventToMultiple({
    required String? content,
    required int? kind,
    required List<String>? recipientPubkeys,
    required List<String>? relays,
    List<List<String>>? tags,
    String? customPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishEncryptedEventToMultiple,
          [],
          {
            #content: content,
            #kind: kind,
            #recipientPubkeys: recipientPubkeys,
            #relays: relays,
            #tags: tags,
            #customPubkey: customPubkey,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.Nip01Event?>>.value(<_i3.Nip01Event?>[]),
      ) as _i5.Future<List<_i3.Nip01Event?>>);

  @override
  _i5.Future<_i3.Ndk> getNdk() => (super.noSuchMethod(
        Invocation.method(
          #getNdk,
          [],
        ),
        returnValue: _i5.Future<_i3.Ndk>.value(_FakeNdk_1(
          this,
          Invocation.method(
            #getNdk,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Ndk>);

  @override
  void setNdkForTesting(_i3.Ndk? ndk) => super.noSuchMethod(
        Invocation.method(
          #setNdkForTesting,
          [ndk],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [HorcruxNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHorcruxNotificationService extends _i1.Mock
    implements _i9.HorcruxNotificationService {
  MockHorcruxNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getBaseUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getBaseUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setBaseUrl(String? override) => (super.noSuchMethod(
        Invocation.method(
          #setBaseUrl,
          [override],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> register({
    required String? fcmToken,
    required _i9.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fcmToken: fcmToken,
            #platform: platform,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deregister() => (super.noSuchMethod(
        Invocation.method(
          #deregister,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateToken({
    required String? newToken,
    required _i9.NotifierPlatform? platform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [],
          {
            #newToken: newToken,
            #platform: platform,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceConsents(List<String>? authorizedSenders) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceConsents,
          [authorizedSenders],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> computeConsentList({
    required String? currentUserPubkey,
    required List<_i10.Vault>? vaults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeConsentList,
          [],
          {
            #currentUserPubkey: currentUserPubkey,
            #vaults: vaults,
          },
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<void> syncConsentList() => (super.noSuchMethod(
        Invocation.method(
          #syncConsentList,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteConsent(String? senderPubkey) => (super.noSuchMethod(
        Invocation.method(
          #deleteConsent,
          [senderPubkey],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> tryPushForEvent({
    required _i3.Nip01Event? event,
    required _i11.NostrKind? kind,
    required _i10.Vault? vault,
    List<String>? relayHints,
    bool? recoveryApproved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryPushForEvent,
          [],
          {
            #event: event,
            #kind: kind,
            #vault: vault,
            #relayHints: relayHints,
            #recoveryApproved: recoveryApproved,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> push({
    required String? recipientPubkey,
    required String? title,
    required String? body,
    Map<String, dynamic>? eventJson,
    String? eventId,
    List<String>? relayHints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [],
          {
            #recipientPubkey: recipientPubkey,
            #title: title,
            #body: body,
            #eventJson: eventJson,
            #eventId: eventId,
            #relayHints: relayHints,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PushNotificationReceiver].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationReceiver extends _i1.Mock
    implements _i12.PushNotificationReceiver {
  MockPushNotificationReceiver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isOptedIn() => (super.noSuchMethod(
        Invocation.method(
          #isOptedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> optIn() => (super.noSuchMethod(
        Invocation.method(
          #optIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> optOut() => (super.noSuchMethod(
        Invocation.method(
          #optOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> maybeInitialize() => (super.noSuchMethod(
        Invocation.method(
          #maybeInitialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
