// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusdbvogEeDJkv7Ig36H2s7unr1z6i5uQ',
    appId: '1:349735517978:web:3eb1d1d032190d7ca6b6a3',
    messagingSenderId: '349735517978',
    projectId: 'horcrux-44113',
    authDomain: 'horcrux-44113.firebaseapp.com',
    storageBucket: 'horcrux-44113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHF-rw0au9mjS_d9W881Qnptx44Zk-SK8',
    appId: '1:349735517978:android:2b4419b7b2c121daa6b6a3',
    messagingSenderId: '349735517978',
    projectId: 'horcrux-44113',
    storageBucket: 'horcrux-44113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJX4_Ca8RullbLwPsMmbq2wpDwL7LlxU',
    appId: '1:349735517978:ios:27612dc5f952b9b7a6b6a3',
    messagingSenderId: '349735517978',
    projectId: 'horcrux-44113',
    storageBucket: 'horcrux-44113.firebasestorage.app',
    iosBundleId: 'com.singleoriginsoftware.horcrux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJX4_Ca8RullbLwPsMmbq2wpDwL7LlxU',
    appId: '1:349735517978:ios:27612dc5f952b9b7a6b6a3',
    messagingSenderId: '349735517978',
    projectId: 'horcrux-44113',
    storageBucket: 'horcrux-44113.firebasestorage.app',
    iosBundleId: 'com.singleoriginsoftware.horcrux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBusdbvogEeDJkv7Ig36H2s7unr1z6i5uQ',
    appId: '1:349735517978:web:ad80fc6486d77b42a6b6a3',
    messagingSenderId: '349735517978',
    projectId: 'horcrux-44113',
    authDomain: 'horcrux-44113.firebaseapp.com',
    storageBucket: 'horcrux-44113.firebasestorage.app',
  );
}
