// Mocks generated by Mockito 5.4.6 from annotations
// in horcrux/test/screens/account_management_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i3;
import 'package:horcrux/services/deep_link_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DeepLinkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkService extends _i1.Mock implements _i2.DeepLinkService {
  @override
  void setNavigatorKey(_i3.GlobalKey<_i3.NavigatorState>? navigatorKey) => super.noSuchMethod(
        Invocation.method(
          #setNavigatorKey,
          [navigatorKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initializeDeepLinking() => (super.noSuchMethod(
        Invocation.method(
          #initializeDeepLinking,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> handleInitialLink() => (super.noSuchMethod(
        Invocation.method(
          #handleInitialLink,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void handleIncomingLink(Uri? uri) => super.noSuchMethod(
        Invocation.method(
          #handleIncomingLink,
          [uri],
        ),
        returnValueForMissingStub: null,
      );

  @override
  ({
    String inviteCode,
    String? ownerName,
    String ownerPubkey,
    List<String> relayUrls,
    String vaultId,
    String? vaultName
  })? parseInvitationLink(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #parseInvitationLink,
          [uri],
        ),
        returnValueForMissingStub: null,
      ) as ({
        String inviteCode,
        String? ownerName,
        String ownerPubkey,
        List<String> relayUrls,
        String vaultId,
        String? vaultName
      })?);
}
